### ISSUE TITLE
TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by yermulnik** [gh640/gh-repo-list#2]
```
> gh extension install gh640/gh-repo-list
Cloning into '/home/giermulnik/.local/share/gh/extensions/gh-repo-list'...
Enter passphrase for key '/home/giermulnik/.ssh/nb.yz.kiev.ua.key':
X11 forwarding request failed
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 19 (delta 4), reused 15 (delta 3), pack-reused 0
Receiving objects: 100% (19/19), 4.74 KiB | 1.58 MiB/s, done.
Resolving deltas: 100% (4/4), done.
✓ Installed extension gh640/gh-repo-list

> gh repo-list
Traceback (most recent call last):
  File "/home/giermulnik/.local/share/gh/extensions/gh-repo-list/gh-repo-list", line 40, in <module>
    def list_commands() -> dict[str, Callable[[], None]]:
TypeError: 'ABCMeta' object is not subscriptable
```
The `python3` resolves on my end to `python3.8`. Changing it to `python3.9` fixes the issue.
It might worth to adjust README with the requirement since now it says it's `Python 3` compatible while it requires at lease `3.9`.
Thanks.

**Comment by yermulnik** [comment]
...or make the script backward compatible with Python 3.8 🤔

**Comment by gh640** [comment]
@yermulnik 

Thanks. Though I've not tested yet, I guess the problem with Python 3.8 is only on the type hint. I'll make the script compatible with Python 3.8 (and 3.7 if easily possible) in a few days.

**Comment by gh640** [comment]
@yermulnik 

I adjusted the type hints to support Python 3.8 (and 3.7) in #3. If you don't mind, please try checking if the HEAD works in your environment.

Related commits:

- https://github.com/gh640/gh-repo-list/commit/d207c1692462af9d21e366bc30ec643dbeec0a02
- https://github.com/gh640/gh-repo-list/commit/ab1827921410d7c5af620b5bdea17ea13c83afe4

**Comment by yermulnik** [comment]
😲
```
> gh extension install gh640/gh-repo-lis
extension is not installable: missing executable
```

**Comment by gh640** [comment]
@yermulnik 

Thanks. Maybe `gh640/gh-repo-lis`, the last `t` is missing?

**Comment by yermulnik** [comment]
Oh 🤦🏻 Copy-paste user error 😂 Thanks for the pointer. I already went with cloning it directly into `~/.local/share/gh/extensions` 😂
It works now w/o issues with Python 3.8. Thanks!

**Comment by gh640** [comment]
@yermulnik 

Yay! Thanks :D
